from typing import List, Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel


class GreenAPIMessage(BaseModel):
    """Model for Green API message"""
    type: str
    id_message: str
    timestamp: int
    type_message: str
    chat_id: str
    sender_id: Optional[str] = None
    sender_name: Optional[str] = None
    sender_contact_name: Optional[str] = None
    text_message: Optional[str] = None
    is_forwarded: Optional[bool] = False
    forwarding_score: Optional[int] = 0
    
    # Additional fields for different message types
    download_url: Optional[str] = None
    caption: Optional[str] = None
    file_name: Optional[str] = None
    is_edited: Optional[bool] = False
    is_deleted: Optional[bool] = False
    
    @property
    def datetime(self) -> datetime:
        """Convert timestamp to datetime"""
        return datetime.fromtimestamp(self.timestamp)
    
    @property
    def is_from_me(self) -> bool:
        """Check if message is from the current user"""
        return self.sender_id == self.chat_id


class ChatConversation(BaseModel):
    """Model for a chat conversation"""
    chat_id: str
    chat_name: Optional[str] = None
    messages: List[GreenAPIMessage]
    last_message_time: datetime
    is_unanswered: bool = False
    
    @property
    def last_message(self) -> Optional[GreenAPIMessage]:
        """Get the last message in the conversation"""
        return self.messages[-1] if self.messages else None


class OpenRouterRequest(BaseModel):
    """Model for OpenRouter API request"""
    model: str
    messages: List[Dict[str, str]]
    max_tokens: Optional[int] = 1000
    temperature: Optional[float] = 0.7


class OpenRouterResponse(BaseModel):
    """Model for OpenRouter API response"""
    choices: List[Dict[str, Any]]
    usage: Optional[Dict[str, Any]] = None


class PriorityReport(BaseModel):
    """Model for priority report generated by AI"""
    urgent_conversations: List[Dict[str, Any]]
    important_conversations: List[Dict[str, Any]]
    normal_conversations: List[Dict[str, Any]]
    summary: str
    total_conversations: int


class DashboardStats(BaseModel):
    """Model for dashboard statistics"""
    total_messages: int
    unanswered_conversations: int
    urgent_conversations: int
    last_analysis_time: datetime
    active_chats: int
